spring:
  profiles:
    default: dev
  config:
    import: optional:file:.env[.properties]
---
spring:
  config:
    activate:
      on-profile: dev
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
---
spring:
  config:
    activate:
      on-profile: prod
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
