spring:
  profiles:
    active: prod
---
spring:
  config:
    activate:
      on-profile: dev
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
---
spring:
  config:
    activate:
      on-profile: prod
  servlet:
    multipart:
      max-file-size: 10MB # 운영환경은 조금 더 제한적으로
      max-request-size: 10MB
