{
 "title": "MySQL 개요",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "MySQL 연결수", "type": "timeseries", "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 } },
  {
   "title": "MySQL 쿼리",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "mysql_global_status_commands_total"
    }
   ]
  },
  {
   "title": "활성 연결",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "mysql_global_status_threads_connected"
    }
   ]
  },
  {
   "title": "초당 쿼리",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(mysql_global_status_questions[5m])"
    }
   ]
  }
 ]
}