version: "3.8"

services:
  app-green:
    image: chisae/pyeondongbu-app:latest
    container_name: app-green
    expose:
      - "8082"
    ports:
      - "8082:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - PROD_DB_HOST=app-db-1
      - PROD_DB_PORT=3306
      - PROD_DB_NAME=pyeon
      - PROD_DB_USERNAME=${PROD_DB_USERNAME}
      - PROD_DB_PASSWORD=${PROD_DB_PASSWORD}
      - SPRING_DATASOURCE_URL=jdbc:mysql://app-db-1:3306/pyeon?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=${PROD_DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${PROD_DB_PASSWORD}
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
      - SPRING_DATA_REDIS_HOST=app-redis-1
      - SPRING_DATA_REDIS_PORT=6379
      - SPRING_DATA_REDIS_PASSWORD=${PROD_REDIS_PASSWORD}
      - PROD_REDIS_HOST=app-redis-1
      - PROD_REDIS_PORT=6379
      - PROD_REDIS_PASSWORD=${PROD_REDIS_PASSWORD}
      - PROD_SERVER_PORT=8080
      - PROD_JWT_SECRET=${PROD_JWT_SECRET_KEY}
      - PROD_GOOGLE_CLIENT_ID=${PROD_GOOGLE_CLIENT_ID}
      - PROD_GOOGLE_CLIENT_SECRET=${PROD_GOOGLE_CLIENT_SECRET}
      - PROD_GOOGLE_REDIRECT_URI=${PROD_GOOGLE_REDIRECT_URI}
      - PROD_AWS_ACCESS_KEY=${PROD_AWS_ACCESS_KEY}
      - PROD_AWS_SECRET_KEY=${PROD_AWS_SECRET_KEY}
      - PROD_AWS_REGION=${PROD_AWS_REGION}
      - PROD_S3_BUCKET=${PROD_S3_BUCKET}
      - PROD_S3_FOLDER=${PROD_S3_FOLDER}
      - PROD_CORS_ORIGIN=${PROD_CORS_ORIGIN}
      - PROD_DOMAIN=api.pyeondongbu.com
      - PROD_FRONTEND_URL=${PROD_FRONTEND_URL}
    restart: always
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

networks:
  app-network:
    external: true
    name: app_app-network
