global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "spring-actuator"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["app-blue:8080", "app-green:8080"]

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "mysql"
    static_configs:
      - targets: ["app-mysqld-exporter:9104"]
    metrics_path: "/metrics"
